# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: sidebar
#  product: List of SOS Tests
#  levels: three
  version: 

  folders:
  
#  - title: IOOS SOS Tests
#    output: web, pdf
#    url: /sos-test-list-summary.html

#    folderitems:

#    - title: Overview
#      url: /sos-test-list-summary.html
#      output: web, pdf

  - title: IOOS SOS Tests
    output: web, pdf

    folderitems:

    - title: OWS Common Tests
      url: /sos-test-list-summary.html#ows-common-tests
      output: web, pdf

    - title: General SOS Tests
      url: /sos-test-list-summary.html#general-sos-tests
      output: web, pdf

    - title: Core SOS Tests
      url: /sos-test-list-summary.html#core-sos-tests
      output: web, pdf

      subfolders:

      - title: GetCapabilities Tests
        output: web, pdf
        subfolderitems:

        - title: OGC General Tests
          url: /sos-test-list-summary.html#ogc-general-tests
          output: web, pdf

        - title: IOOS-specific Tests
          url: /sos-test-list-summary.html#ioos-specific-tests
          output: web, pdf

      - title: DescribeSensor Tests
        output: web, pdf
        subfolderitems:

        - title: OGC General Tests
          url: /sos-test-list-summary.html#ogc-general-tests-1
          output: web, pdf

        - title: IOOS-specific Tests
          url: /sos-test-list-summary.html#ioos-specific-tests-1
          output: web, pdf

      - title: GetObservation Tests
        output: web, pdf
        subfolderitems:

        - title: OGC General Tests
          url: /sos-test-list-summary.html#ogc-general-tests-2
          output: web, pdf

        - title: IOOS-specific Tests
          url: /sos-test-list-summary.html#ioos-specific-tests-2
          output: web, pdf

        



