# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: IOOS SOS Operation Response Templates
  version: 1.0

  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: GetCapability
    url: 
    output: web, pdf

    folderitems:

    - title: Generic Response
      url: /sos-getcapabilities.html
      output: web

  - title: DescribeSensor
    url:
    output: web, pdf

    folderitems:

    - title: Single Station
      url: /sml-describesensor-station.html
      output: web

    - title: Network of Stations
      url: /sml-describesensor-network.html
      output: web, pdf

  - title: GetObservation
    url:
    output: web, pdf

    folderitems:

    - title: Common OM Metadata Part
      url: /om-getobservation.html
      output: web

#    - title: Result Block - TimeSeries
#      url:
#      output: web

      subfolders:

      - title: Result Block for TimeSeries
        output: web, pdf

        subfolderitems:

        - title: Single Station
          url: /swe-singlestation-singleproperty-timeseries.html
          output: web, pdf

        - title: Multiple Stations
          url: /swe-multistation-timeseries.html
          output: web, pdf

        - title: Multiple Stations with QC Flags
          url: /swe-multistation-timeseries-qc.html
          output: web, pdf

      - title: Result Block for TimeSeriesProfile
        output: web, pdf

        subfolderitems:

        - title: Single Station
          url: /swe-singlestation-timeseriesprofile.html
          output: web, pdf

        - title: Single Station with QC Flags
          url: /swe-singlestation-timeseriesprofile-qc.html
          output: web, pdf
