name: iooswkshp
channels:
  - conda-forge
dependencies:
  - python=3.6
  - erddapy
  - folium
  - gdal=2.2
  - geopandas
  - requests
  - scipy
  - xarray
  # Jupyter notebook
  - ipykernel
  - jupyter
  - nb_conda_kernels
  - xlrd
  # R packages
  - r-base==3.4.1
  - r-irkernel
  - rstudio
  - r-classint
  - r-crosstalk
  - r-deldir
  - r-devtools
  - r-dplyr
  - r-dt
  - r-dygraphs
  - r-finch
  - r-forcats
  - r-geor
  - r-geosphere
  - r-ggplot2
  - r-glue
  - r-gstat
  - r-hdf5r
  - r-htmlwidgets
  - r-knitr
  - r-leaflet
  - r-leaflet.extras
  - r-lidr
  - r-lubridate
  - r-magrittr
  - r-mapdata
  - r-mapedit
  - r-maptools
  - r-mapview
  - r-ncdf4
  - r-obistools
  - r-osmar
  - r-plotly
  - r-proj4
  - r-purrr
  - r-randomfields
  - r-randomfieldsutils
  - r-raster
  - r-rastervis
  - r-rcolorbrewer
  - r-readr
  - r-readxl
  - r-rgdal
  - r-rgeos
  # - r-grid
  - r-ritis
  - r-rlang
  - r-rmarkdown
  - r-rnetcdf
  - r-robis
  - r-rvest
  - r-sf
  - r-shiny
  - r-sp
  - r-spacetime
  - r-spatial
  - r-spatstat
  - r-spatstat.data
  - r-spatstat.utils
  - r-spdep
  - r-stringr
  - r-taxize
  - r-taxizesoap
  - r-tibble
  - r-tidyr
  - r-tidyverse
  # - r-tmap
  - r-uuid
  - r-wikidatar
  - r-wikipedir
  - r-wikitaxa

